import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#8FC5FF" },
    content: { flexGrow: 1, padding: 24, paddingTop: 20, paddingBottom: 40 },
    titulo: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#1A2E4A",
        textAlign: "center",
        marginBottom: 20,
    },
    formulario: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 24,
    },
    infoMedico: {
        backgroundColor: "#EBF4FF",
        borderRadius: 10,
        padding: 14,
        marginBottom: 20,
    },
    infoMedicoLabel: { fontSize: 12, color: "#2563A8", fontWeight: "600" },
    infoMedicoNome: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#1A5BA8",
        marginTop: 2,
    },
    label: { fontSize: 14, fontWeight: "600", color: "#555", marginBottom: 4 },
    hint: { fontSize: 12, color: "#999", marginBottom: 12 },
    dataSelecionada: {
        fontSize: 14,
        color: "#2563A8",
        fontWeight: "600",
        textAlign: "center",
        marginTop: 4,
        marginBottom: 16,
        backgroundColor: "#EBF4FF",
        borderRadius: 8,
        padding: 10,
    },
    campoValorTravado: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 8,
        padding: 12,
        marginBottom: 4,
        backgroundColor: "#f5f5f5",
    },
    campoValorTexto: { fontSize: 15, color: "#555", fontWeight: "500" },
    campoValorBloqueado: { fontSize: 12, color: "#aaa" },
    input: {
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 8,
        padding: 12,
        fontSize: 15,
        marginBottom: 16,
        color: "#333",
    },
    inputMultilinha: { height: 80, textAlignVertical: "top" },
    aviso: {
        backgroundColor: "#fff8e1",
        borderLeftWidth: 4,
        borderLeftColor: "#f9a825",
        borderRadius: 6,
        padding: 12,
        marginBottom: 16,
    },
    avisoTexto: { fontSize: 13, color: "#6d4c00", lineHeight: 18 },
    erroTexto: {
        color: "#c0392b",
        fontSize: 13,
        marginBottom: 12,
        textAlign: "center",
    },
    botao: {
        backgroundColor: "#2563A8",
        borderRadius: 10,
        padding: 15,
        alignItems: "center",
    },
    botaoDesabilitado: { backgroundColor: "#93BCEB" },
    botaoTexto: { color: "#fff", fontSize: 16, fontWeight: "bold" },
});
