import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#8FC5FF" },
    loadingContainer: {
        flex: 1,
        backgroundColor: "#8FC5FF",
        justifyContent: "center",
        alignItems: "center",
    },
    content: { flexGrow: 1, padding: 24, paddingTop: 20, paddingBottom: 40 },
    titulo: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#1A2E4A",
        textAlign: "center",
        marginBottom: 20,
    },
    formulario: { backgroundColor: "#fff", borderRadius: 16, padding: 24 },
    avisoBox: {
        backgroundColor: "#fff3cd",
        borderLeftWidth: 4,
        borderLeftColor: "#ffc107",
        borderRadius: 6,
        padding: 12,
        marginBottom: 20,
    },
    avisoTexto: { fontSize: 13, color: "#856404", lineHeight: 18 },
    infoMedico: {
        backgroundColor: "#EBF4FF",
        borderRadius: 10,
        padding: 14,
        marginBottom: 20,
    },
    infoLabel: { fontSize: 12, color: "#2563A8", fontWeight: "600" },
    infoNome: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#1A5BA8",
        marginTop: 2,
    },
    infoEsp: { fontSize: 13, color: "#666", marginTop: 2 },
    label: {
        fontSize: 14,
        fontWeight: "600",
        color: "#555",
        marginBottom: 4,
        marginTop: 4,
    },
    input: {
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 8,
        padding: 12,
        fontSize: 15,
        marginBottom: 4,
        color: "#333",
    },
    hint: { fontSize: 12, color: "#999", marginBottom: 16 },
    erroTexto: {
        color: "#c0392b",
        fontSize: 13,
        marginBottom: 12,
        textAlign: "center",
    },
    botao: {
        backgroundColor: "#2563A8",
        borderRadius: 10,
        padding: 15,
        alignItems: "center",
        marginTop: 4,
    },
    botaoDesabilitado: { backgroundColor: "#93BCEB" },
    botaoTexto: { color: "#fff", fontSize: 16, fontWeight: "bold" },
});
